[package]
name = "swarm-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
swarm-domain = { path = "../swarm-domain" }
swarm-persistence = { path = "../swarm-persistence" }
thiserror.workspace = true

[lints]
workspace = true
